repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.394
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pdm-project/pdm
    rev: 2.22.3
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync
      - id: pdm-export
        args: ['-o', 'requirements.txt', '--without-hashes']
